window.KOTOBALINK_DEMO_DATA = {
  student: {
    name: "小林美咲",
    level: { zh: "初级", ja: "初級" },
    membership: { zh: "课程服务期内会员有效", ja: "コース提供期間中は会員有効" },
    course: { zh: "日语初级精品班", ja: "日本語初級プレミアムクラス" },
    className: { zh: "2026 春季 1 班", ja: "2026 春学期 1組" },
    teacher: { zh: "山田老师", ja: "山田先生" },
    goal: { zh: "6 个月内达到生活与工作基础沟通", ja: "6か月で生活・仕事の基礎会話に到達" },
    renewal: { zh: "当前正常服务期内，预计 6 月进入续费跟进", ja: "現在は通常提供期間中、6月頃から更新フォロー予定" },
  },
  metrics: {
    leads: 18,
    courseOrders: 9,
    memberships: 12,
    activeStudents: 16,
    totalCourses: 6,
    totalClasses: 9,
    totalStudents: 32,
    attendanceRate: "92%",
    homeworkRate: "88%",
    dailyTaskRate: "84%",
    renewalRate: "76%",
    revenue: "¥28,600",
    refunds: 1,
  },
  schedule: [
    { date: "3/12 19:30", title: { zh: "第 5 课 生活会话", ja: "第5課 生活会話" }, status: { zh: "即将开始", ja: "まもなく開始" } },
    { date: "3/14 19:30", title: { zh: "第 6 课 场景表达", ja: "第6課 場面表現" }, status: { zh: "已排课", ja: "時間割確定" } },
  ],
  courses: [
    { name: { zh: "日语 0 起步基础课", ja: "日本語ゼロスタート基礎コース" }, type: { zh: "基础课程", ja: "基礎コース" }, duration: { zh: "持续开放", ja: "常時開放" }, benefit: { zh: "会员权益内", ja: "会員特典内" }, status: { zh: "上架中", ja: "公開中" } },
    { name: { zh: "日语初级精品班", ja: "日本語初級プレミアムクラス" }, type: { zh: "精品课程", ja: "上級コース" }, duration: { zh: "6 个月", ja: "6か月" }, benefit: { zh: "购课送会员权益", ja: "購入で会員特典付与" }, status: { zh: "招生中", ja: "募集中" } },
    { name: { zh: "日语生活会话强化班", ja: "日本語生活会話強化クラス" }, type: { zh: "精品课程", ja: "上級コース" }, duration: { zh: "3 个月", ja: "3か月" }, benefit: { zh: "购课送会员权益", ja: "購入で会員特典付与" }, status: { zh: "待开班", ja: "開講待ち" } },
  ],
  leads: [
    { name: "山口奈奈", level: { zh: "零基础", ja: "ゼロ初級" }, goal: { zh: "赴日生活", ja: "訪日生活" }, status: { zh: "待跟进", ja: "要フォロー" } },
    { name: "陈语晴", level: { zh: "初级", ja: "初級" }, goal: { zh: "工作沟通", ja: "仕事の会話" }, status: { zh: "已沟通", ja: "連絡済み" } },
    { name: "佐藤健", level: { zh: "零基础", ja: "ゼロ初級" }, goal: { zh: "兴趣学习", ja: "趣味学習" }, status: { zh: "待试听", ja: "体験待ち" } },
  ],
  membershipPlans: [
    { name: { zh: "月度会员", ja: "月額会員" }, duration: { zh: "30 天", ja: "30日" }, price: "¥99", benefits: { zh: "基础课程、会员价、每日任务、消息提醒", ja: "基礎コース、会員価格、日次タスク、通知" } },
    { name: { zh: "季度会员", ja: "四半期会員" }, duration: { zh: "90 天", ja: "90日" }, price: "¥299", benefits: { zh: "基础课程、会员价、活动权益、每日任务、消息提醒", ja: "基礎コース、会員価格、イベント特典、日次タスク、通知" } },
  ],
  classmates: [
    { name: "小林美咲", status: { zh: "正常学习", ja: "通常学習" }, progress: { zh: "任务达标", ja: "タスク達成" } },
    { name: "高桥真由", status: { zh: "待跟进", ja: "要フォロー" }, progress: { zh: "昨日任务未完成", ja: "昨日タスク未完了" } },
    { name: "李可欣", status: { zh: "正常学习", ja: "通常学習" }, progress: { zh: "作业已点评", ja: "課題フィードバック済み" } },
  ],
  resources: [
    { title: { zh: "自我介绍语音提交", ja: "自己紹介音声提出" }, type: { zh: "口语作业", ja: "会話課題" }, course: { zh: "日语初级精品班", ja: "日本語初級プレミアムクラス" }, status: { zh: "启用中", ja: "有効" } },
    { title: { zh: "生活场景词汇练习", ja: "生活場面語彙練習" }, type: { zh: "词汇练习", ja: "語彙練習" }, course: { zh: "日语 0 起步基础课", ja: "日本語ゼロスタート基礎コース" }, status: { zh: "启用中", ja: "有効" } },
    { title: { zh: "助词选择题 01", ja: "助詞選択問題 01" }, type: { zh: "语法题", ja: "文法問題" }, course: { zh: "日语初级精品班", ja: "日本語初級プレミアムクラス" }, status: { zh: "草稿", ja: "下書き" } },
  ],
  activity: {
    title: { zh: "春季日语交流沙龙", ja: "春の日本語交流サロン" },
    type: { zh: "公开活动", ja: "公開イベント" },
    fee: "¥99",
    time: "3/20 14:00",
    location: { zh: "东京池袋交流空间", ja: "東京池袋交流スペース" },
    status: { zh: "已报名", ja: "申込済み" },
    desc: { zh: "以生活会话和破冰交流为主题，帮助学员把课堂表达带到真实场景中。", ja: "生活会話とアイスブレイク交流をテーマに、授業表現を実際の場面へつなげます。" },
  },
  homework: {
    title: { zh: "自我介绍语音提交", ja: "自己紹介音声提出" },
    due: { zh: "明晚 22:00", ja: "明日 22:00" },
    feedback: { zh: "表达自然，发音较好，建议语速再放慢一点。", ja: "表現は自然で発音も良好です。もう少しゆっくり話すとさらに良くなります。" },
    score: "A-",
  },
  dailyTask: {
    vocab: ["駅", "電車", "歩きます", "今日", "明日"],
    grammarCount: 3,
    streak: 12,
  },
  demoState: {
    purchased: true,
    homeworkSubmitted: true,
    dailyTaskCompleted: false,
    currentRole: "admin",
    currentAdminPage: "admin-dashboard",
    currentMiniPage: "mini-home",
    operatorDashboardView: "operations",
    sidebarCollapsed: false,
    launchGuideEnterpriseFocus: false,
    locale: "zh",
  },
  followups: [
    { name: "高桥真由", reason: { zh: "昨日每日任务未完成", ja: "昨日の日次タスク未完了" }, owner: { zh: "运营-A", ja: "運営-A" } },
    { name: "王小雨", reason: { zh: "作业逾期待跟进", ja: "課題期限超過で要フォロー" }, owner: { zh: "山田老师", ja: "山田先生" } },
  ],
  orders: [
    { no: "KL20260310001", item: { zh: "日语初级精品班", ja: "日本語初級プレミアムクラス" }, type: { zh: "课程", ja: "コース" }, amount: "¥6,980", status: { zh: "已支付", ja: "支払済み" }, user: "小林美咲" },
    { no: "KL20260310002", item: { zh: "春季交流活动", ja: "春の交流イベント" }, type: { zh: "活动", ja: "イベント" }, amount: "¥99", status: { zh: "已支付", ja: "支払済み" }, user: "小林美咲" },
    { no: "KL20260310003", item: { zh: "季度会员", ja: "四半期会員" }, type: { zh: "会员", ja: "会員" }, amount: "¥299", status: { zh: "退款处理中", ja: "返金処理中" }, user: "高桥真由" },
  ],
  refunds: [
    { no: "RF20260310001", orderNo: "KL20260310003", item: { zh: "季度会员", ja: "四半期会員" }, user: "高桥真由", reason: { zh: "重复下单", ja: "重複注文" }, status: { zh: "人工审核中", ja: "手動審査中" } },
  ],
  notifications: [
    { title: { zh: "明晚 19:30 有课程安排", ja: "明日19:30に授業予定があります" }, type: { zh: "上课提醒", ja: "授業通知" } },
    { title: { zh: "今日每日任务待完成", ja: "本日の日次タスクが未完了です" }, type: { zh: "任务提醒", ja: "タスク通知" } },
    { title: { zh: "作业反馈已更新", ja: "課題フィードバックが更新されました" }, type: { zh: "反馈提醒", ja: "フィードバック通知" } },
  ],
};
