window.KOTOBALINK_DEMO_DATA = {
  student: {
    name: "小林美咲",
    level: "初级",
    membership: "课程服务期内会员有效",
    course: "日语初级精品班",
    className: "2026 春季 1 班",
    teacher: "山田老师",
    goal: "6 个月内达到生活与工作基础沟通",
    renewal: "当前正常服务期内，预计 6 月进入续费跟进",
  },
  metrics: {
    leads: 18,
    courseOrders: 9,
    memberships: 12,
    activeStudents: 16,
    totalCourses: 6,
    totalClasses: 9,
    totalStudents: 32,
    attendanceRate: "92%",
    homeworkRate: "88%",
    dailyTaskRate: "84%",
    renewalRate: "76%",
    revenue: "¥28,600",
    refunds: 1,
  },
  schedule: [
    { date: "3/12 19:30", title: "第 5 课 生活会话", status: "即将开始" },
    { date: "3/14 19:30", title: "第 6 课 场景表达", status: "已排课" },
  ],
  courses: [
    { name: "日语 0 起步基础课", type: "基础课程", duration: "持续开放", benefit: "会员权益内", status: "上架中" },
    { name: "日语初级精品班", type: "精品课程", duration: "6 个月", benefit: "购课送会员权益", status: "招生中" },
    { name: "日语生活会话强化班", type: "精品课程", duration: "3 个月", benefit: "购课送会员权益", status: "待开班" },
  ],
  leads: [
    { name: "山口奈奈", level: "零基础", goal: "赴日生活", status: "待跟进" },
    { name: "陈语晴", level: "初级", goal: "工作沟通", status: "已沟通" },
    { name: "佐藤健", level: "零基础", goal: "兴趣学习", status: "待试听" },
  ],
  membershipPlans: [
    { name: "月度会员", duration: "30 天", price: "¥99", benefits: "基础课程、会员价、每日任务、消息提醒" },
    { name: "季度会员", duration: "90 天", price: "¥299", benefits: "基础课程、会员价、活动权益、每日任务、消息提醒" },
  ],
  classmates: [
    { name: "小林美咲", status: "正常学习", progress: "任务达标" },
    { name: "高桥真由", status: "待跟进", progress: "昨日任务未完成" },
    { name: "李可欣", status: "正常学习", progress: "作业已点评" },
  ],
  resources: [
    { title: "自我介绍语音提交", type: "口语作业", course: "日语初级精品班", status: "启用中" },
    { title: "生活场景词汇练习", type: "词汇练习", course: "日语 0 起步基础课", status: "启用中" },
    { title: "助词选择题 01", type: "语法题", course: "日语初级精品班", status: "草稿" },
  ],
  activity: {
    title: "春季日语交流沙龙",
    type: "公开活动",
    fee: "¥99",
    time: "3/20 14:00",
    location: "东京池袋交流空间",
    status: "已报名",
    desc: "以生活会话和破冰交流为主题，帮助学员把课堂表达带到真实场景中。",
  },
  homework: {
    title: "自我介绍语音提交",
    due: "明晚 22:00",
    feedback: "表达自然，发音较好，建议语速再放慢一点。",
    score: "A-",
  },
  dailyTask: {
    vocab: ["駅", "電車", "歩きます", "今日", "明日"],
    grammarCount: 3,
    streak: 12,
  },
  demoState: {
    purchased: true,
    homeworkSubmitted: true,
    dailyTaskCompleted: false,
    currentRole: "admin",
    currentAdminPage: "admin-dashboard",
    currentMiniPage: "mini-home",
    operatorDashboardView: "operations",
    sidebarCollapsed: false,
    launchGuideEnterpriseFocus: false,
    locale: "zh",
  },
  followups: [
    { name: "高桥真由", reason: "昨日每日任务未完成", owner: "运营-A" },
    { name: "王小雨", reason: "作业逾期待跟进", owner: "山田老师" },
  ],
  orders: [
    { no: "KL20260310001", item: "日语初级精品班", type: "课程", amount: "¥6,980", status: "已支付", user: "小林美咲" },
    { no: "KL20260310002", item: "春季交流活动", type: "活动", amount: "¥99", status: "已支付", user: "小林美咲" },
    { no: "KL20260310003", item: "季度会员", type: "会员", amount: "¥299", status: "退款处理中", user: "高桥真由" },
  ],
  refunds: [
    { no: "RF20260310001", orderNo: "KL20260310003", item: "季度会员", user: "高桥真由", reason: "重复下单", status: "人工审核中" },
  ],
  notifications: [
    { title: "明晚 19:30 有课程安排", type: "上课提醒" },
    { title: "今日每日任务待完成", type: "任务提醒" },
    { title: "作业反馈已更新", type: "反馈提醒" },
  ],
};
